# Fill in your Redis connection information.
database:
  host: 'localhost'
  port: 6379
  password: ''
# Wait timeout(seconds)
# If set to 0, no wait timeout is applied (unlimited wait).
preemption-wait-timeout: 30